In [10]:
import numpy

In [12]:
array1 = numpy.array([2, 3, 5, 7, 11, 13])

In [13]:
array1

array([ 2,  3,  5,  7, 11, 13])

In [14]:
type(array1)

numpy.ndarray

In [15]:
array1.shape

(6,)

In [18]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [19]:
type(array2)

numpy.ndarray

In [20]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
array2.shape

(3, 4)

In [23]:
array1.size

6

In [24]:
array2.size

12

In [26]:
array3 = numpy.full(6,7)

print(array3)

[7 7 7 7 7 7]


In [30]:
array4 = numpy.full(6,0)
array5 = numpy.zeros(6, dtype=int)

print(array4)
print()
print(array5)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [35]:
array6 = numpy.full(5,1)
array7 = numpy.ones(5, dtype=int)
print(array6)
print()
print(array7)

[1 1 1 1 1]

[1 1 1 1 1]


In [36]:
array8 = numpy.random.random(3)
print(array8)

[0.77208715 0.05725761 0.90595288]


In [37]:
array9 = numpy.arange(5)
print(array9)

[0 1 2 3 4]


In [39]:
array10 = numpy.arange(1, 9)
print(array10)

[1 2 3 4 5 6 7 8]


In [42]:
array11 = numpy.arange(3, 17, 3)
print(array11)

[ 3  6  9 12 15]
